### ISSUE TITLE
Week 9 Rahim and Yagnik

### ISSUE THREAD

**Issue by rahkhadi** [rahkhadi/PRJ-team#17]
@rahkhadi and @YagnikDankhara will work on Agile completed user stories, Business Rules and Domain class Diagram

**Comment by YagnikDankhara** [comment]
![Domain Class Diagram](https://github.com/user-attachments/assets/955d89e6-5257-43a6-b81b-64819b6713c9)

**Comment by rahkhadi** [comment]
[Agile Completed User Stories.docx](https://github.com/user-attachments/files/16229374/Agile.Completed.User.Stories.docx)
